num_agents:
  min: 30000
  max: 49999
recommended_min_ram: 16384
cache_limits:
  num_counters: 160000
  max_cost: 209715200
server_limits:
  policy_throttle: 2ms
  max_connections: 32000
  checkin_limit:
    interval: 500us
    burst: 4000
    max: 15001
  artifact_limit: 
    interval: 500us
    burst: 4000
    max: 8000
  enroll_limit: 
    interval: 10ms
    burst: 100
    max: 200
  ack_limit:
    interval: 500us
    burst: 4000
    max: 8000
