name: Issue Triage
on:
  issues:
    types: [labeled,unlabeled]
  pull_request:
    types: [labeled,unlabeled]
jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign labelled issues to projects
    steps:
      - name: Assign to repo and user projects
        uses: richkuz/github-actions/project-assigner@v2.1.0
        id: project_assigner
        with:
          issue-mappings: |
            [
              {"label": "Team:Agent", "projectNumber": "478", "columnName": "Inbox", "projectScope": "org"}
            ]

          ghToken: ${{ secrets.ELASTIC_ORG_GITHUB_ACTIONS_TOKEN }}
